namespace IDosGames
{
	public static class PlayFabReturnMessage
	{
		public const string KEY_MESSAGE = "Message";

		public const string REFERRAL_MESSAGE_CODE_INCORRECT = "REFERRAL_MESSAGE_CODE_INCORRECT";
		public const string REFERRAL_MESSAGE_CODE_ALREADY_ACTIVATED = "REFERRAL_MESSAGE_CODE_ALREADY_ACTIVATED";
		public const string REFERRAL_MESSAGE_CODE_YOUR = "REFERRAL_MESSAGE_CODE_YOUR";
		public const string REFERRAL_MESSAGE_CODE_SUCCESS_ACTIVATED = "REFERRAL_MESSAGE_CODE_SUCCESS_ACTIVATED";
		public const string REFERRAL_MESSAGE_CODE_SUCCESS_CHANGED = "REFERRAL_MESSAGE_CODE_SUCCESS_CHANGED";

		public const string SHOP_MESSAGE_CODE_ITEMS_GRANTED = "SHOP_MESSAGE_CODE_ITEMS_GRANTED";
		public const string SHOP_MESSAGE_CODE_NOT_ENOUGH_FUNDS = "SHOP_MESSAGE_CODE_NOT_ENOUGH_FUNDS";
	}
}